
theme: jekyll-theme-cayman
> title: > The Framing of Environmental Issues in Chinese Media
> description: > <i>Discussion of Climate Change&#8212;a Comparative Study 
> description: > <b>« Green mountains and clear water are equal to mountains of gold and silver. »</b>&#12316;Xi Jinping</i>

menu: [
{'name': 'Overview', 'pagename': 'index'},
{'name': 'I. Sources and Methodology', 'pagename': 'page6'},
{'name': 'II. Media and Government', 'pagename': 'page1'},
{'name': 'III. Prototypes', 'pagename': 'page2'},
{'name': 'IV. Topic Modeling', 'pagename': 'page3'},
{'name': 'V. Contingency Matrix', 'pagename': 'page4'},
{'name': 'VI. Network Analysis', 'pagename': 'page5'},
{'name': 'VII. Criticality Index', 'pagename': 'page7'},
{'name': 'Contact & Comments', 'pagename': 'page8'},
]
