
theme: jekyll-theme-cayman
title: The Framing of Environmental Issues in Chinese Media
description: <i>The Discussion of Climate Change-a Comparative Analysis</i>
menu: [
{'name': 'Home', 'pagename': 'index'},
{'name': 'Demography', 'pagename': 'page1'},
{'name': 'Clusters', 'pagename': 'page2'},
{'name': 'Topic Modeling', 'pagename': 'page3'},
{'name': 'Extras', 'pagename': 'page4'},

    /* The image used */
    background-image: url("china-environment/assets/images/Background1.jpg");

    /* Full height */
    height: 100%; 

    /* Center and scale the image nicely */
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}

