
theme: jekyll-theme-leap-day
title: The Framing of Environmental Issues in China
description: And this is the textual description of your website 
menu: [
{'name': 'Home', 'pagename': 'index'},
{'name': 'Demography', 'pagename': 'page1'},
{'name': 'Clusters', 'pagename': 'page2'},
{'name': 'Topic Modeling', 'pagename': 'page3'},
{'name': 'Extras', 'pagename': 'page4'},
]
