
theme: jekyll-theme-cayman
title: The Framing of Environmental Issues in China
description: And this is the textual description of your website 
menu: [
{'name': 'Home', 'pagename': 'index'},
{'name': 'Demography', 'pagename': 'page1'},
{'name': 'Clusters', 'pagename': 'page2'},
{'name': 'Topic Modeling', 'pagename': 'page3'},
{'name': 'Extras', 'pagename': 'page4'},

<html>
<head>
<style>
body, html {
    height: 100%;
    margin: 0;
}

.bg {
    /* The image used */
    background-image: url("Background1.jpg");

    /* Full height */
    height: 100%; 

    /* Center and scale the image nicely */
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
}
</style>
</head>
<body>

