
theme: jekyll-theme-cayman
title: The Framing of Environmental Issues in Chinese Media
description: <i>Discussion of Climate Change&#8212;a Comparative Study - <b>« Green mountains and clear water are equal to mountains of gold and silver. »<b> - Xi Jinping<i>

menu: [
{'name': 'Overview', 'pagename': 'index'},
{'name': 'Historical Analysis', 'pagename': 'page1'},
{'name': 'Prototypes', 'pagename': 'page2'},
{'name': 'Topic Modelling', 'pagename': 'page3'},
{'name': 'Contingency Matrix', 'pagename': 'page4'},
{'name': 'Network Analysis', 'pagename': 'page5'},
{'name': 'Media and Government', 'pagename': 'page6'},
]
